version: '3.3'

# Networks --------------------------------------------------------------------

networks:
  default:
    external:
      name: di-proxy

# Services --------------------------------------------------------------------

services:

  # -- MySQL

  db-app:
    image: mysql:5.7
    container_name: di-db
    ports:
      - ${PORT_DB}:3306
    volumes:
      - ${DATA_PATH}/db:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_APP_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_APP_DATABASE}
      MYSQL_USER: ${DB_APP_USERNAME}
      MYSQL_PASSWORD: ${DB_APP_PASSWORD}

  # -- FPM

  php-fpm:
    container_name: api-fpm
    build:
      context: ./api/.config
      dockerfile: php-fpm.dockerfile
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - ./api:/var/www

  # -- Web

  api-app:
    image: nginx:latest
    container_name: api-web
    ports:
      - ${PORT_API}:80
    environment:
      VIRTUAL_HOST: api.dealerinspire.local
    restart: unless-stopped
    volumes:
      - ./api/.config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./api/storage/logs/nginx:/var/log/nginx
      - ./api:/var/www

  web-app:
    image: nginx:latest
    container_name: app-web
    ports:
      - ${PORT_WEB}:80
    environment:
      VIRTUAL_HOST: dealerinspire.local
    restart: unless-stopped
    volumes:
      - ./frontend/.config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/.logs:/var/log/nginx
      - ./frontend/public:/var/www/public

# Volumes ---------------------------------------------------------------------

volumes:
  api:
  frontend:
